id = "systemrdl"
name = "SystemRDL"
version = "0.0.1"
schema_version = 1
authors = ["Citorva <contact@citorva.fr>"]
description = "SystemRDL Language Support"
repository = "https://github.com/citorva/systemrdl-zed"

[grammars.systemrdl]
repository = "https://github.com/citorva/tree-sitter-systemrdl"
commit = "4302f3d70b33911b88c1e4d6622ec2f88de68f3d"
